services:
  postgres:
    image: timescale/timescaledb:latest-pg18@sha256:2c718e700b1c75b93488085596f2254c991c3aa29584fc282ebbe62fd8335791
    ports:
      - 15432:5432
    env_file:
      - .env
    environment:
      TIMESCALEDB_TELEMETRY: "off"
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/db-data/:/var/lib/postgresql/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:40fa840c5bb7c8463957f1255b01283732c2d8c9396a956d180f8e6c296753b3
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/pgadmin-data/:/var/lib/pgadmin/
    post_start:
      - command: chown --recursive 5050:0 /var/lib/pgadmin/
        user: root

networks:
  postgres-network:
    driver: bridge
