services:
  postgres:
    image: timescale/timescaledb:latest-pg18@sha256:253c1a62938c1a756a03be67a0ab1d357e9dead95380de7dd52d036e9a792e7b
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/db-data/:/var/lib/postgresql/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:cefc4cc6b7d9d71a9e81e76fb9d7e14038ab5661b539a190eea1b63fa612589a
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/pgadmin-data/:/var/lib/pgadmin/
    post_start:
      - command: chown --recursive 5050:0 /var/lib/pgadmin/
        user: root

networks:
  postgres-network:
    driver: bridge
