services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/vscode/
    depends_on:
      - timescaledb
    network_mode: service:timescaledb
    command: sleep infinity

  timescaledb:
    image: timescale/timescaledb:2.28.2-pg18@sha256:bb208a255ce7d44d8d6bed4e9e8059b532be4f56fd6d6d962e37d270bfadf1bd
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - timescaledb-data:/var/lib/postgresql/
      - ../init-db/:/docker-entrypoint-initdb.d/

volumes:
  timescaledb-data:
