services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/vscode/
    depends_on:
      - timescaledb
    network_mode: service:timescaledb
    command: sleep infinity

  timescaledb:
    image: timescale/timescaledb:2.28.0-pg18@sha256:c5af2474aaa0f619b3dd288991c1d309ec702f3fb318b0491862366e3c152da9
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - timescaledb-data:/var/lib/postgresql/
      - ../init-db/:/docker-entrypoint-initdb.d/

volumes:
  timescaledb-data:
